export const AUTH = {
  SET_LOGIN_STATUS: "SET_LOGIN_STATUS",
  SET_VOTED_CANDIDATE: "SET_VOTED_CANDIDATE",
  RESET: "RESET",
  SET_ELIGIBLE: "SET_ELIGIBLE",
};

export const VOTING = {
  GET_ALL_CANDIDATE: "GET_ALL_CANDIDATE",
  CAST_YOUR_VOTES: "CAST_YOUR_VOTES",
  CHECK_ALREADY_VOTED: "CHECK_ALREADY_VOTED",
  GET_WINNER: "GET_WINNER",
  SET_VOTED_CANDIDATE: "SET_VOTED_CANDIDATE",
  SET_VOTE_TIME: "SET_VOTE_TIME",
};
